server:
  port: 8094
  servlet:
    context-path: /eureka-server-2
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:8091/eureka-server/eureka